export const RENDER_CONFIG = {
  hardwareScalingLevel: 1,
  clearColor: "#1F242BFF",
  imageProcessing: {
    toneMappingEnabled: false,
    exposure: 1.0,
    contrast: 1.0,
  },
  lighting: {
    environmentUrl: "/environment.env",
    iblIntensity: 0.35,
    sunIntensity: 1.0,
    sunDirection: { x: -0.4, y: -1.0, z: -0.3 },
    hemiFillEnabled: true,
    hemiIntensity: 0.25,
    hemiGroundColor: "#262626",
    hemiDiffuseColor: "#FFFFFF",
    hemiSpecularColor: "#333333",
    studioThreePoint: {
      enabled: true,
      target: { x: 0, y: 1.25, z: 0 },
      key: {
        position: { x: -2.4, y: 3.2, z: 2.8 },
        intensity: 40,
        color: "#FFF1DA",
        angle: 0.85,
        exponent: 1.8,
      },
      fill: {
        position: { x: 2.6, y: 2.1, z: 2.0 },
        intensity: 10,
        color: "#DDEBFF",
        angle: 1.1,
        exponent: 1.3,
      },
      rim: {
        position: { x: 1.5, y: 2.7, z: -2.8 },
        intensity: 10,
        color: "#E8F5FF",
        angle: 0.75,
        exponent: 2.2,
      },
    },
  },
  shadows: {
    mapSize: 2048,
    usePercentageCloserFiltering: true,
  },
  environmentBackground: {
    useGroundProjection: false,
    groundProjectionSize: 1000,
    groundProjectionRadius: 20,
    groundProjectionHeight: 1.5,
  },
};
